# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      #image: ghcr.io/zina-420001498/gitversion:0.1.0
      image: ghcr.io/zina-420001498/gcc8-with-coverity:0.5.0
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Ru step in Container
        shell: bash
        run: |
          # Whatever commands you want to run here using the container with your
          # new Docker image at ghcr.io!>
          echo "--This is running in my custom Docker image--"
          ls
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
     

